<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Features/Financial/ReferenceData/iso-4217-country-codes.xml"
      LogicalName="Stocktrac.Domain.Features.Financial.ReferenceData.iso-4217-country-codes.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
  </ItemGroup>
</Project>